### ISSUE TITLE
react－sample里面hello.js没有import react－dom，报错

### ISSUE THREAD

**Issue by pfan123** [dwqs/react_practice#2]
react－sample里面hello.js没有import react－dom，报错

**Comment by hongqi** [comment]
这个加了react-dom也跑不通啊？？？

**Comment by hongqi** [comment]
entry.js 改成

var ReactDOM = require('react-dom');
var React = require('react');
var Hello = require('./Hello');

ReactDOM.render(<Hello name="Nate" />, document.body);

Hello.js 最后加上
module.exports = Hello;


这样改就好了
